bookshop/bookshop/urls.py
from django.contrib import admin
from catalog import views
from django.urls import path, include, re_path

urlpatterns = [
    path('', views.index, name='index'),
    path('authors_add/', views.authors_add, name='authors_add'),
    path('edit1/<int:id>/', views.edit1, name='edit1'),
    path('create/', views.create, name='create'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('admin/', admin.site.urls),
    path('books/', views.BookListView.as_view(), name='books'),
    re_path(r'^book/(?P<pk>\d+)$', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
]

urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book_create'),
    re_path(r'^book/update/(?P<pk>\d+)$', views.BookUpdate.as_view(), name='book_update'),
    re_path(r'^book/delete/(?P<pk>\d+)$', views.BookDelete.as_view(), name='book_delete'),
    path('accounts/', include('django.contrib.auth.urls')),
]

bookshop/catalog/models.py
from django.urls import reverse
from django.db import models

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=200,
                            help_text="Введите жанр книги",
                            verbose_name="Жанр книги")

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите язык книги",
                            verbose_name="Язык книги")

    def __str__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=100,
                                  help_text="Введите имя автора",
                                  verbose_name="Имя")
    last_name = models.CharField(max_length=100,
                                 help_text="Введите фамилию автора",
                                 verbose_name="Фамилия")
    date_of_birth = models.DateField(help_text="Введите дату рождения",
                                     verbose_name="Дата рождения",
                                     null=True, blank=True)
    date_of_death = models.DateField(help_text="Введите дату смерти",
                                     verbose_name="Дата смерти",
                                     null=True, blank=True)

    def __str__(self):
        return self.last_name


class Book(models.Model):
    title = models.CharField(max_length=200,
                             help_text="Введите название книги",
                             verbose_name="Название")
    genre = models.ForeignKey('Genre', on_delete=models.CASCADE,
                              help_text="Выберите жанр книги",
                              verbose_name="Жанр", null=True)
    language = models.ForeignKey('Language', on_delete=models.CASCADE, null=True,
                                 help_text="Выберите язык книги",
                                 verbose_name="Язык книги")
    author = models.ManyToManyField('Author',
                                    help_text="Выберите автора книги",
                                    verbose_name="Автор книги",)
    summary = models.TextField(max_length=1000,
                               help_text="Введите краткое описание книги",
                               verbose_name="Описание")
    isbn = models.CharField(max_length=13,
                            help_text="Должно быть 13 символов",
                            verbose_name="ISBN")

    def __str__(self):
        return self.title

    def display_author(self):
        return ', '.join([author.last_name for author in
                          self.author.all()])

    display_author.short_description = 'Авторы'

    def get_absolute_url(self):
        return reverse('book-detail', args=[str(self.id)])

class Status(models.Model):
    name = models.CharField(max_length=20,
                            help_text="Введите статус книги",
                            verbose_name="Статус")

    def __str__(self):
        return self.name

class BookInstance(models.Model):
    book = models.ForeignKey('Book', on_delete=models.CASCADE, null=True,)
    inv_nom = models.CharField(max_length=20, null=True,
                               help_text="Введите инвентарный номер книги",
                               verbose_name="Инвентарный номер")
    imprint = models.CharField(max_length=200,
                               help_text="Введите издательство и год выпуска",
                               verbose_name="Издательство")
    status = models.ForeignKey('Status', on_delete=models.CASCADE,
                               null=True,
                               help_text="Измените статус книги",
                               verbose_name="Статус")
    due_back = models.DateField(null=True, blank=True,
                                help_text="Введите конец срока статуса",
                                verbose_name="Дата окончания срока")

    def __str__(self):
        return '%s %s %s' % (self.inv_nom, self.book, self.status)




bookshop/catalog/forms.py
from django import forms
from datetime import date
from django.forms import ModelForm
from .models import Book


class AuthorsForm(forms.Form):
    first_name = forms.CharField(label="Имя автора")
    last_name = forms.CharField(label="Фамилия автора")
    date_of_birth = forms.DateField(label="Дата рождения", initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))
    date_of_death = forms.DateField(label="Дата смерти", initial=format(date.today()),
                                    widget=forms.widgets.DateInput(attrs={'type': 'date'}))

class BookModelForm(ModelForm):
    class Meta:
        model = Book
        fields = ['title', 'genre', 'language', 'author', 'summary', 'isbn']


bookshop/catalog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Author, Book, BookInstance, Genre
from django.views import generic
from django.views.generic import DetailView
from .forms import AuthorsForm
from django.http import *
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Book


def index(request):
    #return HttpResponse("Главная страница БукШопа!")
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact=2).count()
    num_authors = Author.objects.count()

    return render(request, 'index.html',
                  context={'num_books': num_books,
                           'num_instances': num_instances,
                           'num_instances_available': num_instances_available,
                           'num_authors': num_authors,},
                  )

class BookListView(generic.ListView):
    model = Book

class BookDetailView(generic.DetailView):
    model = Book

class AuthorListView(generic.ListView):
    model = Author

def authors_add(request):
    author = Author.objects.all()
    authorsform = AuthorsForm()
    return render(request, "catalog/authors_add.html", {"form": authorsform, "author": author})

def create(request):
    if request.method == "POST":
        author = Author()
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")

def delete(request, id):
    try:
        author = Author.objects.get(id=id)
        author.delete()
        return HttpResponseRedirect("/authors_add/")
    except Author.DoesNotExist:
        return HttpResponseNotFound("<h2>Автор не найден</h2>")

def edit1(request, id):
    author = Author.objects.get(id=id)
    if request.method == "POST":
        author.first_name = request.POST.get("first_name")
        author.last_name = request.POST.get("last_name")
        author.date_of_birth = request.POST.get("date_of_birth")
        author.date_of_death = request.POST.get("date_of_death")
        author.save()
        return HttpResponseRedirect("/authors_add/")
    else:
        return render(request, "edit1.html", {"author": author})

class BookCreate(CreateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookUpdate(UpdateView):
    model = Book
    fields = '__all__'
    success_url = reverse_lazy('books')


class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books')


bookshop/catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block title %}<title>Мир книг</title>{% endblock %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,
    initial-scale=l">
    {% load static %}
    <style>
    /* General body styles */
body {
    font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif;
    color: #333;
    background-image: url('{% static "background.png" %}');
    background-size: cover;
    margin: 0;
    padding: 0;
}

/* Header styles */
h1 {
    color: #2c3e50; /* Dark blue shade */
    text-align: center;
}

h2 {
    color: #2c3e50; /* Dark blue shade */
    text-align: center;
}

/* Navigation sidebar styles */
.sidebar-nav li {
    list-style: none;
}

.sidebar-nav a {
    text-decoration: none;
    color: #3498db;
    display: block;
    padding: 10px;
    text-align: center;
}

/* Pagination styles */
.pagination {
    text-align: center;
    padding: 20px 0;
}

.page-links a {
    color: #3498db;
    margin: 0 5px;
    text-decoration: none;
}

.page-current {
    color: #2c3e50;
}

/* Footer styles */
footer {
    color: #2c3e50;
    text-align: center;
    padding: 20px 0;
    position: absolute;
    bottom: 0;
    width: 100%;
}
p {
text-align: center;
color: #2c3e50;
}

ul {
    list-style-type: none;
    padding: 0;
    margin: 0;
    text-align: center;
}
h4 {
    color: #2c3e50; /* Dark blue shade */
    text-align: center;
}
.copyright {
    color: #2c3e50;
    padding: 10px;
    margin: 0;
    width: 100%;
    text-align: center;
}
table {
    margin-left: auto;
    margin-right: auto;
}
h3 {
    color: #2c3e50; /* Dark blue shade */
    text-align: center;
}
input {
  display: block; margin: 0 auto;
  padding: 8px 15px;
  border: 1px solid #ccc;
  border-radius: 4px;
  box-shadow: 0 2px 5px rgba(0,0,0,0.1);
  transition: all 0.3s ease;
}
</style>
    {% block head %}
        <h1>Сеть книжных магазинов БукШоп</h1>
    {% endblock %}
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2">
            {% block sidebar %}
            <ul class="sidebar-nav">
                <li><a href="{% url 'index' %}">Главная страница</a></li>
                <li><a href="{% url 'books' %}">Bce книги</a></li>
                <li><a href="{% url 'authors' %}">Все авторы</a></li>
                <li><a href="{% url 'authors_add' %}">Редактировать авторов</a></li>
                <li><a href="{% url 'book_create' %}">Добавить книгу</a></li>
              {% if user.is_authenticated %}
                <li>Пользователь: {{ user.get_username }}</li>
                <li><a href="{% url 'logout'%}?next={{request.path}}">Выход</a></li>
              {% else %}
                <li><a href="{% url 'login'%}?next={{request.path}}">Вход</a></li>
              {% endif %}
            </ul>
            {% endblock %}
            </div>
            <div class="col-sm-10 ">
            {% block content %}{% endblock %}
                {% block pagination %}
                    {% if is_paginated %}
                        <div class="pagination">
                            <span class="page-links">
                                {% if page_obj.has_previous %}
                                    <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                                {% endif %}
                                <span class="page-current">
                                    Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                                </span>
                                {% if page_obj.has_next %}
                                    <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                                {% endif %}
                            </span>
                        </div>
            {% endif %}
        {% endblock %}
            {% block footer %}
                {% block copyright %}
            <p class="copyright">Copyright ООО "Книги БукШоп", 2024. Все права не защищены</p>
                {% endblock %}
            {% endblock %}
            </div>
        </div>
    </div>
</body>
</html>

bookshop/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список авторов в БД</h1>

    {% if author_list %}
     {% for author in author_list.all %}
        <p>{{ author.first_name}}  {{author.last_name}},
           <strong>Родился-</strong>{{author.date_of_birth}},
           <strong>Умер-</strong>{{author.date_of_death}}</p>
     {% endfor %}
    {% else %}
      <p>В базе данных нет авторов</p>
    {% endif %}
{% endblock %}

bookshop/catalog/templates/catalog/authors_add.html
{% extends "base_generic.html" %}
{% block content %}

  <h3>Список авторов в БД</h3>
   <table>
        <thead>
            <th>Id</th><th>----Имя----</th><th>Фамилия</th><th></th>
        </thead>
  {% if author %}
     {% for author in author.all %}
        <tr>
           <td>{{author.id}}</td>
           <td>{{author.first_name}}</td>
           <td>{{author.last_name}}</td>
           <td><a href="/edit1/{{author.id}}">Изменить</a> , <a href="/delete/{{author.id}}">Удалить</a></td>
        </tr>
     {% endfor %}
  {% else %}
      <p>В базе данных нет авторов</p>
  {% endif %}
    </table>

<h3>Добавить в БД автора книги</h3>
<form method="POST" action="/create/">
        {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type="submit" value="Сохранить" >
</form>
{% endblock %}

bookshop/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Удаление книги</h1>
<p> Вы уверены, что хотите удалить книгу: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Да, удалить" />
</form>

{% endblock %}

bookshop/catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Название книги: {{ book.title }}</h1>

  <p><strong>Жанр:</strong> {{ book.genre }}</p>
  <p><strong>Аннотация:</strong> {{ book.summary }}</p>
  <p><strong>ISBN:</strong> {{ book.isbn }}</p>
  <p><strong>Язык:</strong> {{ book.language }}</p>
     {% for author in book.author.all %}
        <p><strong>Автор:</strong> <a href="{% url 'authors' %}">{{ author.first_name }}  {{author.last_name}}</a></p>
     {% endfor %}

<div style="margin-left:20px;margin-top:20px">
    <h4>Количество экземпляров книг в БД</h4>
    {% for copy in book.bookinstance_set.all %}
       <hr><p class="{% if copy.status == 1 %} text-success
                 {% elif copy.status == 2 %} text-danger
                 {% else %} text-warning
                 {% endif %}"> {{ copy.get_status_display }}</p>
       <p><strong>Издательство:</strong> {{copy.imprint}}</p>
       <p class="text-muted"><strong>Инвентарный номер:</strong> {{copy.id}}</p>
       <p><strong>Статус экземпляра книги в БД:</strong> {{copy.status}}</p>
    {% endfor %}
  </div>
{% endblock %}

bookshop/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Сохранить">

</form>
{% endblock %}

bookshop/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список книг в БД</h1>
    {% if book_list %}
    <ul>
      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">
            {{ book.title }}</a>
            ({{ book.genre }})
        <a href="/book/update/{{book.id}}">Изменить</a>
        <a href="/book/delete/{{book.id}}">Удалить</a>
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>В базе данных нет книг</p>
    {% endif %}
{% endblock %}

bookshop/catalog/templates/edit1.html
{% extends "base_generic.html" %}
{% block content %}

  <h3>Текущие сведения об авторе</h3>
  <h4>{{author.first_name}} {{author.last_name}} ({{author.date_of_birth}} - {{author.date_of_death}})</h4>

    <form method="POST">
        {% csrf_token %}
        <h3>Изменить сведения об авторе книги</h3>
        <p> <label>Измените имя</label><br>
            <input type="text" name="first_name" value="{{author.first_name}}" />
        </p>
        <p> <label>Измените фамилию</label><br>
            <input type="text" name="last_name" value="{{author.last_name}}" />
        </p>
        <p> <label>Измените дату рождения</label><br>
            <input type="date"  name="date_of_birth"  value="{{author.date_of_birth}}"/>
        </p>
        <p> <label>Измените дату смерти</label><br>
            <input type="date" name="date_of_death" value="{{author.date_of_death}}" />
        </p>
        <input type="submit" value="Сохранить" >
    </form>

{% endblock %}

bookshop/catalog/templates/index.html
{% extends "base_generic.html" %}
<style>

</style>
{% block content %}
<h1>Главная страница</h1>

  <p>Добро пожаловать в БукШоп!<br> Это веб-сайт одноименной компании по продаже книг, написанный на Django.<br>
     Проект является собственностью и показателем знания разработчика Vokich.</p>

<h2>Динамический контент</h2>

  <p>База данных сайта БукШоп содержит следующее количество записей:</p>
  <ul>
    <li><strong>Количество книг:</strong> {{ num_books }}</li>
    <li><strong>Количество экземпляров книг:</strong> {{ num_instances }}</li>
    <li><strong>Количество экземпляров книг в заказе:</strong> {{ num_instances_available }}</li>
    <li><strong>Количество авторов книг:</strong> {{ num_authors }}</li>
  </ul>
{% endblock %}